## Data Manipulation and Analysis with NumPy

**Definition:** NumPy is a fundamental package for scientific computing with Python. It provides support for arrays, matrices, and a large collection of mathematical functions to operate on these data structures. NumPy arrays are more efficient and provide better performance for numerical operations compared to Python's built-in lists.

**Use Case in Real Life:** NumPy can be used in various scientific computing scenarios, such as statistical analysis, signal processing, and image processing.

### Creating a NumPy Array from a List

In [27]:
pip install numpy

In [1]:
import numpy as np

# Creating a 1D array from a list
arr1 = np.array([1, 2, 3, 4, 5])
print(arr1)

# Creating a 2D array from a list of lists
arr2 = np.array([[1, 2, 3], [4, 5, 6]])
print(arr2)

[1 2 3 4 5]
[[1 2 3]
 [4 5 6]]


### Creating Arrays with Functions

In [2]:
# Creating an array of zeros
zeros = np.zeros((3, 4))
print(zeros)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [3]:
# Creating an array of ones
ones = np.ones((2, 3))
print(ones)

[[1. 1. 1.]
 [1. 1. 1.]]


In [4]:
# Creating an array with a range of values
range_arr = np.arange(10, 20, 2)
print(range_arr)

[10 12 14 16 18]


In [29]:
# Creating an array with random values
random_arr = np.random.rand(3, 3)
print(random_arr)

[[0.19239396 0.78458601 0.45453701]
 [0.28580424 0.78197998 0.94837409]
 [0.79865136 0.86638824 0.45441141]]


### Basic Array Operations - Element-wise Operations

In [31]:
arr1

array([1, 2, 3, 4, 5])

In [35]:
for i in arr1:
  print(i+2)

3
4
5
6
7


In [6]:
arr = np.array([1, 2, 3, 4, 5])

# Element-wise addition
print(arr + 2)

[3 4 5 6 7]


In [7]:
# Element-wise multiplication
print(arr * 2)

[ 2  4  6  8 10]


In [8]:
# Element-wise subtraction
print(arr - 1)

[0 1 2 3 4]


In [9]:
# Element-wise division
print(arr / 2)

[0.5 1.  1.5 2.  2.5]


### Basic Array Operations - Mathematical Functions

In [10]:
arr = np.array([1, 2, 3, 4, 5])

# Square root
print(np.sqrt(arr))

[1.         1.41421356 1.73205081 2.         2.23606798]


In [11]:
# Exponential
print(np.exp(arr))

[  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]


In [12]:
# Logarithm
print(np.log(arr))

[0.         0.69314718 1.09861229 1.38629436 1.60943791]


In [13]:
# Sine
print(np.sin(arr))

[ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427]


### Indexing and Slicing - Indexing

In [14]:
arr = np.array([1, 2, 3, 4, 5])

# Accessing elements
print(arr[0])  # First element
print(arr[-1]) # Last element

1
5


### Indexing and Slicing - Slicing

In [15]:
arr = np.array([1, 2, 3, 4, 5])

# Slicing array
print(arr[1:4])  # Elements from index 1 to 3
print(arr[:3])   # First three elements
print(arr[2:])   # Elements from index 2 to the end

[2 3 4]
[1 2 3]
[3 4 5]


### Indexing and Slicing - Advanced Indexing

In [16]:
arr = np.array([1, 2, 3, 4, 5])

# Boolean indexing
print(arr[arr > 3])

# Fancy indexing
indices = [0, 2, 4]
print(arr[indices])

[4 5]
[1 3 5]


### Reshaping and Transposing - Reshaping Arrays

In [17]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

# Reshaping the array
reshaped = arr.reshape((3, 2))
print(reshaped)

[[1 2]
 [3 4]
 [5 6]]


### Reshaping and Transposing - Transposing Arrays

In [18]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

# Transposing the array
transposed = arr.T
print(transposed)

[[1 4]
 [2 5]
 [3 6]]


### Aggregation Functions - Sum and Mean

In [19]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

# Sum of all elements
print(np.sum(arr))

21


In [20]:
# Sum along columns
print(np.sum(arr, axis=0))

[5 7 9]


In [21]:
# Sum along rows
print(np.sum(arr, axis=1))

[ 6 15]


In [22]:
# Mean of all elements
print(np.mean(arr))

3.5


### Aggregation Functions - Min and Max

In [23]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

# Minimum value
print(np.min(arr))

1


In [24]:
# Maximum value
print(np.max(arr))

6


In [25]:
# Index of minimum value
print(np.argmin(arr))

0


In [26]:
# Index of maximum value
print(np.argmax(arr))

5


### Thank you